"""initial schema

Revision ID: 963216a3b694
Revises: 
Create Date: 2026-03-25 12:19:36.983724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963216a3b694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_acres', sa.Float(), nullable=False),
    sa.Column('pasture_acres', sa.Float(), nullable=False),
    sa.Column('broccoli_acres', sa.Float(), nullable=False),
    sa.Column('young_cattle_acres', sa.Float(), nullable=False),
    sa.Column('flower_acres', sa.Float(), nullable=False),
    sa.Column('fallow_acres', sa.Float(), nullable=False),
    sa.Column('non_productive_acres', sa.Float(), nullable=False),
    sa.Column('milking_cows', sa.Integer(), nullable=False),
    sa.Column('young_cattle', sa.Integer(), nullable=False),
    sa.Column('milk_per_cow_per_day', sa.Float(), nullable=False),
    sa.Column('broccoli_tons_per_hectare', sa.Float(), nullable=False),
    sa.Column('broccoli_cycles_per_year', sa.Float(), nullable=False),
    sa.Column('milk_price_per_liter', sa.Float(), nullable=False),
    sa.Column('broccoli_price_per_ton', sa.Float(), nullable=False),
    sa.Column('flower_annual_revenue', sa.Float(), nullable=False),
    sa.Column('num_workers', sa.Integer(), nullable=False),
    sa.Column('worker_monthly_salary', sa.Float(), nullable=False),
    sa.Column('manager_pct_of_revenue', sa.Float(), nullable=False),
    sa.Column('manager_wife_pct_of_revenue', sa.Float(), nullable=False),
    sa.Column('feed_cost_per_cow_per_month', sa.Float(), nullable=False),
    sa.Column('crop_input_cost_per_hectare', sa.Float(), nullable=False),
    sa.Column('vet_annual', sa.Float(), nullable=False),
    sa.Column('fuel_transport_annual', sa.Float(), nullable=False),
    sa.Column('other_costs_annual', sa.Float(), nullable=False),
    sa.Column('hailstorms_per_year', sa.Float(), nullable=False),
    sa.Column('frost_events_per_year', sa.Float(), nullable=False),
    sa.Column('crop_loss_per_hailstorm', sa.Float(), nullable=False),
    sa.Column('crop_loss_per_frost', sa.Float(), nullable=False),
    sa.Column('bull_hailstorms', sa.Float(), nullable=False),
    sa.Column('bull_frost_events', sa.Float(), nullable=False),
    sa.Column('bull_price_modifier', sa.Float(), nullable=False),
    sa.Column('bear_hailstorms', sa.Float(), nullable=False),
    sa.Column('bear_frost_events', sa.Float(), nullable=False),
    sa.Column('bear_price_modifier', sa.Float(), nullable=False),
    sa.Column('max_stocking_rate', sa.Float(), nullable=False),
    sa.Column('min_fallow_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pasture_acres', sa.Float(), nullable=True),
    sa.Column('broccoli_acres', sa.Float(), nullable=True),
    sa.Column('young_cattle_acres', sa.Float(), nullable=True),
    sa.Column('flower_acres', sa.Float(), nullable=True),
    sa.Column('fallow_acres', sa.Float(), nullable=True),
    sa.Column('milking_cows', sa.Integer(), nullable=True),
    sa.Column('young_cattle', sa.Integer(), nullable=True),
    sa.Column('milk_per_cow_per_day', sa.Float(), nullable=True),
    sa.Column('broccoli_tons_per_hectare', sa.Float(), nullable=True),
    sa.Column('broccoli_cycles_per_year', sa.Float(), nullable=True),
    sa.Column('milk_price_per_liter', sa.Float(), nullable=True),
    sa.Column('broccoli_price_per_ton', sa.Float(), nullable=True),
    sa.Column('flower_annual_revenue', sa.Float(), nullable=True),
    sa.Column('num_workers', sa.Integer(), nullable=True),
    sa.Column('worker_monthly_salary', sa.Float(), nullable=True),
    sa.Column('manager_pct_of_revenue', sa.Float(), nullable=True),
    sa.Column('manager_wife_pct_of_revenue', sa.Float(), nullable=True),
    sa.Column('feed_cost_per_cow_per_month', sa.Float(), nullable=True),
    sa.Column('crop_input_cost_per_hectare', sa.Float(), nullable=True),
    sa.Column('vet_annual', sa.Float(), nullable=True),
    sa.Column('fuel_transport_annual', sa.Float(), nullable=True),
    sa.Column('other_costs_annual', sa.Float(), nullable=True),
    sa.Column('hailstorms_per_year', sa.Float(), nullable=True),
    sa.Column('frost_events_per_year', sa.Float(), nullable=True),
    sa.Column('crop_loss_per_hailstorm', sa.Float(), nullable=True),
    sa.Column('crop_loss_per_frost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    op.drop_table('farm_baseline')
    # ### end Alembic commands ###
